comment/urls.py
from django.urls import path
from comment import views


urlpatterns = [
    path("create/", views.comment_create, name="comment-create-api"),
    path("delete/", views.comment_delete, name="comment-delete-api"),
    path("list-parent-comment/",
         views.list_parent_comment, name="api-list-parent-comment"),
    path("list-children-comment/",
         views.list_sub_comment, name="api-list-children-comment"),
]

idea/urls.py
from django.urls import path
from idea import views


urlpatterns = [
    path("create/", views.idea_create, name="idea-create-page"),
    path("update/<slug:slug>/", views.idea_update, name="idea-update-page"),    
    path("delete/<slug:slug>/", views.idea_delete, name="idea-delete-page"),
    path("<slug:slug>/", views.idea_detail, name="idea-detail-page"),
]

whatsidea/urls.py
from django.contrib import admin
from django.urls import path, include
from whatsidea.views import homePage, privacyPage, policyPage
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homePage, name="home-page"),
    path('', include('user.urls')),
    path('idea/', include('idea.urls')),
    path('post/', include('post.urls')),
    path('vote/', include('vote.urls')),
    path('contribution/', include('contribution.urls')),
    path('comment/', include('comment.urls')),
    path('image/', include('image.urls')),
    path('privacy/', privacyPage, name="privacy-page"),
    path('policy/', policyPage, name="policy-page"),
    path('like/', include('like.urls')),
    path('inbox/notifications/',
         include(notifications.urls, namespace='notifications')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import uuid


from notifications.signals import notify


def my_handler(sender, instance, created, **kwargs):
    notify.send(instance, verb='was contributed')


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    phone = models.CharField(max_length=30, blank=True)

    def __str__(self):
        return str(self.user)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Idea(models.Model):
    founder = models.ManyToManyField(User)
    title = models.CharField(max_length=500)
    slug = models.SlugField(max_length=500, unique=True, default=uuid.uuid1)
    shortdesc = models.TextField(blank=True)
    content = models.TextField(default="Have no Idea!")
    is_publish = models.BooleanField(default=True)
    is_success = models.BooleanField(default=False)
    address = models.CharField(max_length=200, blank=True)
    phone = models.CharField(max_length=12, blank=True)
    website = models.CharField(max_length=30, blank=True)
    corver_image = models.ImageField(upload_to="media/", blank=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.title)

    class Meta:
        ordering = ["-date_created"]


class Image(models.Model):
    idea = models.ForeignKey(
        Idea, null=True, blank=True, on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    img_file = models.ImageField(upload_to="image")

    def __str__(self):
        return str(self.img_file.url)


class Post(models.Model):
    idea = models.ForeignKey(Idea, on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    content = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.content)

    class Meta:
        ordering = ["-date_created"]


class Contribution(models.Model):
    idea = models.ForeignKey(
        Idea, on_delete=models.CASCADE, null=True, blank=True)
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    parent = models.ForeignKey(
        "self", blank=True, null=True, related_name="children", on_delete=models.CASCADE)
    content = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["date_created"]

    def __str__(self):
        return str(self.content)


@receiver(post_save, sender=Contribution)
def add_notification(sender, instance, **kwargs):
    user_list = instance.idea.founder.all()
    print(instance)
    for user in user_list:
        notify.send(instance.user, recipient=user,
                    verb='contributed', action_object=instance, target=instance.idea)


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, null=True, blank=True)
    parent = models.ForeignKey(
        "self", blank=True, null=True, related_name="children", on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    content = models.TextField()
    date_create = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.content)


class Vote(models.Model):
    idea = models.ForeignKey(
        Idea, null=True, blank=True, on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    contribution = models.ForeignKey(
        Contribution, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return "user:%s  idea:%s" % (str(self.user), str(self.idea))


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_create = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(
        Post, null=True, blank=True, on_delete=models.CASCADE)
    comment = models.ForeignKey(
        Comment, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return "user:%s post:%s" % (str(self.user), str(self.post))

comment/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponse
import json
from core import models
from django.core import serializers
from django.template.loader import render_to_string
from django.core.paginator import Paginator


def list_parent_comment(request):
    post_id = request.GET.get('post_id')
    post = get_object_or_404(models.Post, id=post_id)
    comment_query = post.comment_set.filter(parent__isnull=True)
    print(post)

    paginator = Paginator(comment_query, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    rended_comment = render_to_string(
        template_name="comment/list-comment.html",
        context={
            "page_obj": page_obj,
        }, request=request
    )

    if page_obj.has_next():
        return JsonResponse({
            "page_number": page_obj.next_page_number(),
            "comment": rended_comment
        })
    else:
        return JsonResponse({
            "comment": rended_comment
        })


def list_sub_comment(request):
    parent_id = request.GET.get('parent_id')
    comment = get_object_or_404(models.Comment, id=parent_id)
    comment_query = comment.children.all()

    paginator = Paginator(comment_query, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    rended_comment = render_to_string(
        template_name="comment/list-children-comment.html",
        context={
            "page_obj": page_obj,
        }, request=request
    )

    if page_obj.has_next():
        return JsonResponse({
            "page_number": page_obj.next_page_number(),
            "comment": rended_comment
        })
    else:
        return JsonResponse({
            "comment": rended_comment
        })


@login_required()
def comment_create(request):

    data = json.loads(request.body)
    post_id = data["post_id"]
    content = data["content"]

    if "parent_id" in data:
        parent_id = data["parent_id"]
        parent = models.Comment.objects.get(id=parent_id)
    else:
        parent = None

    post = models.Post.objects.get(id=post_id)
    comment = models.Comment.objects.create(
        user=request.user,
        post=post,
        parent=parent,
        content=content
    )

    rended_comment = render_to_string(
        template_name="comment/comment.html",
        context={
            "comment": comment
        },
        request=request
    )

    print("comment created: ", comment)

    return JsonResponse({
        "message": "comment created",
        "comment": rended_comment
    })


@login_required()
def comment_delete(request):

    data = json.loads(request.body)
    comment_id = data["comment_id"]

    comment = get_object_or_404(models.Comment, id=comment_id)
    comment.delete()

    return JsonResponse({
        "message": "comment deleted",
        "comment": {
            "id": comment.id,
        }
    })

templates/comment/comment-area.html
<!-- Load comment by ajax and apend comment here -->
<div id="list-comment-{{post.id}}">
</div>

<div id="btn-load-more-comment" class="btn btn-load-more-comment" data-next_page_number="1"
    data-post_id="{{ post.id }}">Load more ...
    <div class="spinner-border spinner-border-sm loading d-none" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</div>

<!-- delete comment -->
<div class="modal fade" tabindex="-1" role="dialog" aria-hidden="true" id="confirm-delete-comment">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Are you sure to delete this?</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default btn-comment-delete">Yes</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>


<!-- create comment-->
<form method="POST" id="create-comment-form-{{post.id}}" class="mt-3 create-new-comment-form"
    data-post_id="{{ post.id }}">
    <div class="text-center loading mb-3 d-none">
        <div class="spinner-border spinner-border-sm" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <div class="border-left-secondary input-group">
        <textarea class="form-control" name="content" placeholder="Some comments..."></textarea>
        <div class="input-group-append">
            <button class="btn btn-outline-secondary btn-create-comment" type="submit">Send</button>
        </div>
    </div>
    {% if not user.is_authenticated %}
    <p><a href="{% url 'user-login-page' %}?next={{ request.path }}">Login</a> required to make
        comment!</p>
    {% endif %}
</form>

templates/comment/comment.html
{% load voted %}

<div class="mt-3 px-2 border-left-info" id="comment-{{ comment.id }}">
    <div class="comment-content">
        <p class="m-0"> {{ comment }} </p>
    </div>
    <div class="p-0">
        <div class="mr-3">
            <a href="{% url 'user-detail-page' comment.user %}">@{{ comment.user }}</a>
            <span>{{ comment.date_created | date:"d/m/y H:i"}}</span>
        </div>
        <div class="navbar p-0 justify-content-start">

            <!-- Comment count, comment or not -->
            <div class="{{ comment.like_set.all|voted:user }} btn text-decoration-none btn-like-comment "
                data-comment_id="{{ comment.id }}">
                <span class="h5">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                        class="bi bi-heart" viewBox="0 0 16 16">
                        <path fill-rule="evenodd"
                            d="M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z" />
                    </svg>
                </span>
                <span class="comment-count">
                    {% if comment.like_set.all.count > 0 %}
                    {{ comment.like_set.all.count }}
                    {% endif %}
                </span>
            </div>

            <!-- If comment is chidrent, form it point to is #children-comment-form-{{ comment.parent.id }}-->
            {% if comment.parent is Null %}
            <span class="btn btn-reply cursor-pointer" data-toggle="collapse"
                data-target="#children-comment-form-{{ comment.id }}" data-comment_id="{{ comment.id }}">Reply</span>
            {% else %}
            <span class="btn btn-reply cursor-pointer" data-toggle="collapse"
                data-target="#children-comment-form-{{ comment.parent.id }}"
                data-comment_id="{{ comment.id }}">Reply</span>
            {% endif %}

            <!-- If user owns this comment, this user can delete -->
            <div class="dropup">
                <span class="mr-3 btn cursor-pointer" data-toggle="dropdown"> More</span>
                <div class="dropdown-menu dropdown-menu-right">
                    {% if user == comment.user  %}
                    <a class="dropdown-item cursor-pointer" data-toggle="modal" data-target="#confirm-delete-comment"
                        data-parent-comment_id="{{ comment.parent.id }}" data-comment_id="{{comment.id}}">Delete</a>
                    {% else %}
                    <a class="dropdown-item cursor-not-allowed">Report</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

templates/comment/list-children-comment.html
{% for comment in page_obj %}
<div class="children-comment" id="children-comment-{{ comment.id }}">
    {% include "comment/comment.html" with comment=comment %}
</div>
{% endfor %}

templates/comment/list-comment.html
{% for comment in page_obj %}
<div id="parent-comment-{{ comment.id }}">
    {% include "comment/comment.html" with comment=comment %}

    <!-- Append list childrens comment here -->
    <div id="list-children-comment-{{ comment.id }}" class="ml-3"></div>
    {% if comment.children.all.count > 0 %}
    <div class="btn btn-load-more-comment" id="btn-load-more-children-comment-{{ comment.id }}"
        data-next_page_number="1" data-parent_id="{{ comment.id }}">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
            class="bi bi-arrow-return-right" viewBox="0 0 16 16">
            <path fill-rule="evenodd"
                d="M1.5 1.5A.5.5 0 0 0 1 2v4.8a2.5 2.5 0 0 0 2.5 2.5h9.793l-3.347 3.346a.5.5 0 0 0 .708.708l4.2-4.2a.5.5 0 0 0 0-.708l-4-4a.5.5 0 0 0-.708.708L13.293 8.3H3.5A1.5 1.5 0 0 1 2 6.8V2a.5.5 0 0 0-.5-.5z" />
        </svg>
        <span class="children-count">{{ comment.children.all.count }}</span>
        <span>more...</span>
        <div class="spinner-border spinner-border-sm loading d-none" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    {% endif %}

    <!-- form create sub comment -->
    <form class="mt-3 collapse ml-3 create-new-comment-form" data-post_id="{{ comment.post.id }}"
        id="children-comment-form-{{ comment.id }}" data-parent_id="{{ comment.id }}">
        <div class="text-center loading mb-3 d-none">
            <div class="spinner-border spinner-border-sm" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <div class="border-left-secondary input-group">
            {% csrf_token %}
            <textarea class="form-control" name="content" placeholder="Some comments..."></textarea>
            <div class="input-group-append">
                <button class="btn btn-outline-secondary btn-create-comment" type="submit">Send</button>
            </div>
        </div>
        {% if not user.is_authenticated %}
        <p><a href="{% url 'user-login-page' %}?next={{ request.path }}">Login</a> required to make
            comment!</p>
        {% endif %}
    </form>
</div>
{% endfor %}