contribution/urls.py
from django.urls import path
from contribution import views


urlpatterns = [
    path("create/", views.contribution_create, name="contribution-create-api"),
    path("delete/", views.contribution_delete, name="contribution-delete-api"),
    path("list-parent-contribution/",
         views.list_parent_contribution, name="api-list-parent-contribution"),
    path("list-children-contribution/",
         views.list_sub_contribution, name="api-list-children-contribution"),
]

idea/urls.py
from django.urls import path
from idea import views


urlpatterns = [
    path("create/", views.idea_create, name="idea-create-page"),
    path("update/<slug:slug>/", views.idea_update, name="idea-update-page"),    
    path("delete/<slug:slug>/", views.idea_delete, name="idea-delete-page"),
    path("<slug:slug>/", views.idea_detail, name="idea-detail-page"),
]

whatsidea/urls.py
from django.contrib import admin
from django.urls import path, include
from whatsidea.views import homePage, privacyPage, policyPage
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homePage, name="home-page"),
    path('', include('user.urls')),
    path('idea/', include('idea.urls')),
    path('post/', include('post.urls')),
    path('vote/', include('vote.urls')),
    path('contribution/', include('contribution.urls')),
    path('comment/', include('comment.urls')),
    path('image/', include('image.urls')),
    path('privacy/', privacyPage, name="privacy-page"),
    path('policy/', policyPage, name="policy-page"),
    path('like/', include('like.urls')),
    path('inbox/notifications/',
         include(notifications.urls, namespace='notifications')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import uuid


from notifications.signals import notify


def my_handler(sender, instance, created, **kwargs):
    notify.send(instance, verb='was contributed')


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    phone = models.CharField(max_length=30, blank=True)

    def __str__(self):
        return str(self.user)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Idea(models.Model):
    founder = models.ManyToManyField(User)
    title = models.CharField(max_length=500)
    slug = models.SlugField(max_length=500, unique=True, default=uuid.uuid1)
    shortdesc = models.TextField(blank=True)
    content = models.TextField(default="Have no Idea!")
    is_publish = models.BooleanField(default=True)
    is_success = models.BooleanField(default=False)
    address = models.CharField(max_length=200, blank=True)
    phone = models.CharField(max_length=12, blank=True)
    website = models.CharField(max_length=30, blank=True)
    corver_image = models.ImageField(upload_to="media/", blank=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.title)

    class Meta:
        ordering = ["-date_created"]


class Image(models.Model):
    idea = models.ForeignKey(
        Idea, null=True, blank=True, on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    img_file = models.ImageField(upload_to="image")

    def __str__(self):
        return str(self.img_file.url)


class Post(models.Model):
    idea = models.ForeignKey(Idea, on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    content = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.content)

    class Meta:
        ordering = ["-date_created"]


class Contribution(models.Model):
    idea = models.ForeignKey(
        Idea, on_delete=models.CASCADE, null=True, blank=True)
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    parent = models.ForeignKey(
        "self", blank=True, null=True, related_name="children", on_delete=models.CASCADE)
    content = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["date_created"]

    def __str__(self):
        return str(self.content)


@receiver(post_save, sender=Contribution)
def add_notification(sender, instance, **kwargs):
    user_list = instance.idea.founder.all()
    print(instance)
    for user in user_list:
        notify.send(instance.user, recipient=user,
                    verb='contributed', action_object=instance, target=instance.idea)


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, null=True, blank=True)
    parent = models.ForeignKey(
        "self", blank=True, null=True, related_name="children", on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    content = models.TextField()
    date_create = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.content)


class Vote(models.Model):
    idea = models.ForeignKey(
        Idea, null=True, blank=True, on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    contribution = models.ForeignKey(
        Contribution, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return "user:%s  idea:%s" % (str(self.user), str(self.idea))


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_create = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(
        Post, null=True, blank=True, on_delete=models.CASCADE)
    comment = models.ForeignKey(
        Comment, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return "user:%s post:%s" % (str(self.user), str(self.post))

contribution/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponse
import json
from core import models
from django.core import serializers
from django.template.loader import render_to_string
from django.core.paginator import Paginator


def list_parent_contribution(request):
    idea_id = request.GET.get('idea_id')
    idea = get_object_or_404(models.Idea, id=idea_id)
    contribution_query = idea.contribution_set.filter(parent__isnull=True)

    paginator = Paginator(contribution_query, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    rended_contribution = render_to_string(
        template_name="contribution/list-contribution.html",
        context={
            "page_obj": page_obj,
        }, request=request
    )

    if page_obj.has_next():
        return JsonResponse({
            "page_number": page_obj.next_page_number(),
            "contribution": rended_contribution
        })
    else:
        return JsonResponse({
            "contribution": rended_contribution
        })


def list_sub_contribution(request):
    parent_id = request.GET.get('parent_id')
    contribution = get_object_or_404(models.Contribution, id=parent_id)
    contribution_query = contribution.children.all()

    paginator = Paginator(contribution_query, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    rended_contribution = render_to_string(
        template_name="contribution/list-children-contribution.html",
        context={
            "page_obj": page_obj,
        }, request=request
    )

    if page_obj.has_next():
        return JsonResponse({
            "page_number": page_obj.next_page_number(),
            "contribution": rended_contribution
        })
    else:
        return JsonResponse({
            "contribution": rended_contribution
        })


@login_required()
def contribution_create(request):

    data = json.loads(request.body)
    idea_id = data["idea_id"]
    content = data["content"]

    if "parent_id" in data:
        parent_id = data["parent_id"]
        parent = models.Contribution.objects.get(id=parent_id)
    else:
        parent = None

    idea = models.Idea.objects.get(id=idea_id)
    contribution = models.Contribution.objects.create(
        user=request.user,
        idea=idea,
        parent=parent,
        content=content
    )

    rended_contribution = render_to_string(
        template_name="contribution/contribution.html",
        context={
            "contribution": contribution
        },
        request=request
    )

    print("contribution created: ", contribution)

    return JsonResponse({
        "message": "contribution created",
        "contribution": rended_contribution
    })


@login_required()
def contribution_delete(request):

    data = json.loads(request.body)
    contribution_id = data["contribution_id"]

    contribution = get_object_or_404(models.Contribution, id=contribution_id)
    contribution.delete()

    return JsonResponse({
        "message": "contribution deleted",
        "contribution": {
            "id": contribution.id,
        }
    })

templates/contribution/contribution-area.html
<!-- Load contribution by ajax and apend contribution here -->
<div id="list-contribution" >
</div>

<div id="btn-load-more-contribution" class="btn btn-load-more-contribution" data-next_page_number="1"
    data-idea_id="{{ idea.id }}">Load more ...
    <div class="spinner-border spinner-border-sm loading d-none" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</div>
<script>
    // load contribution

    // **********
    // Get contribution
    //
    // Ajax function
    // Listen click load event
    // Apeend data
    // ********** 

    function load_more_contribution(url_api) {
        return $.ajax({
            headers: {
                "Content-Type": "application/json",
                "X-CSRFToken": csrftoken
            },
            url: url_api,
            type: "GET",
        })
    }


    // Load comment first time
    (function loadContribution(page_number) {
        let url_api = `{% url 'api-list-parent-contribution' %}?idea_id={{idea.id}}&page=${page_number}`;
        load_more_contribution(url_api).done(res => {
            if (res.page_number) {
                $('#btn-load-more-contribution').data('next_page_number', res.page_number);
            } else
                $('#btn-load-more-contribution').hide();
            $("#list-contribution").append(res.contribution);
        })
    })(1);


    // Click load more contribution and load
    $(document).on("click", ".btn-load-more-contribution", function () {
        // Get next_page_number, parent_id, idea_id from load more button
        let load_btn = $(this);

        // Show loading icon 
        load_btn.find(".loading").removeClass("d-none")
        let page_number = load_btn.data("next_page_number");
        let parent_id = load_btn.data("parent_id");
        let idea_id = load_btn.data("idea_id");
        if (!page_number) return;

        // Check of load parent contribution or children 
        // Load parent contribution
        if (idea_id && !parent_id) {
            console.log("loading parent contribution");
            let url_api = `{% url 'api-list-parent-contribution' %}?idea_id=${idea_id}&page=${page_number}`;
            load_more_contribution(url_api).done(res => {
                if (res.page_number) {
                    load_btn.data('next_page_number', res.page_number);
                    load_btn.find(".loading").addClass("d-none");
                } else {
                    load_btn.hide();
                }
                $("#list-contribution").append(res.contribution);
            })
        }

        // Load children contribution
        if (parent_id && !idea_id) {
            console.log("loading children, parent_id: ", parent_id);
            let url_api =
                `{% url 'api-list-children-contribution' %}?parent_id=${parent_id}&page=${page_number}`;
            load_more_contribution(url_api).done(res => {
                let list_element_id = `#list-children-contribution-${parent_id}`;
                if (res.page_number) {
                    load_btn.data('next_page_number', res.page_number);
                    load_btn.find(".loading").addClass("d-none");

                    // update childrent count: delete loaded 
                    let childrent_count = parseInt(load_btn.find(".children-count").text());
                    childrent_count -= (res.page_number - 1) * 5;
                    load_btn.find(".children-count").text(childrent_count);
                } else {
                    load_btn.hide();
                }
                $(`#list-children-contribution-${parent_id}`).append(res.contribution);
            })
        }
    })



    // ***********
    // Create contribution
    // **********

    // Create contribution 
    let create_contribution_form = $(".create-new-contribution-form");
    $(document).on("submit", ".create-new-contribution-form", function (event) {
        event.preventDefault();
        let collapse_form = $(this);
        collapse_form.find(".loading").removeClass('d-none');
        collapse_form.find(".btn-create-contribution").addClass("disabled")
        let idea_id = $(this).data("idea_id");
        let parent_id = $(this).data("parent_id");
        let form = $(this).serializeJSON();
        create_contribution(idea_id, parent_id, form.content).done(res => {
            collapse_form.find(".loading").addClass('d-none');
            collapse_form.find(".btn-create-contribution").removeClass("disabled")
            if (parent_id)
                $(`#list-children-contribution-${parent_id}`).append(res.contribution);
            else
                $(`#list-contribution`).append(res.contribution);
            collapse_form.find("textarea").val("");
            setTimeout(() => {
                collapse_form.collapse('hide');
            }, 200)
        });
    })

    // Confirm delete contribution modal and delete
    var confirm_delete_contribution = $('#confirm-delete-contribution')
    $(document).on('show.bs.modal', '#confirm-delete-contribution', function (event) {
        console.log("deletecon")
        // Button that triggered the modal
        var button = event.relatedTarget
        // Extract info from data-contribtution-id-* attributes            
        var id = $(button).data('contribution-id');
        let parent_id = $(button).data('parent-contribution-id');
        // Initiate an AJAX request to delete contribution
        // and update the html content 
        $(".btn-contribution-delete").click(function (event) {
            delete_contribution(id).done(res => {
                if (res.message == "contribution deleted") {
                    $('#confirm-delete-contribution').modal('hide');
                    setTimeout(() => {
                        $(`#contribution-${id}`).remove();
                        if (!parent_id) {
                            $(`#parent-contribution-${id}`).remove();
                        }
                    }, 200)
                }
            })
        });
    })

    // Vote contribution
    $(document).on("click", ".btn-contribution-vote", function () {
        let btn = $(this);
        let contribution_id = btn.data("contribution_id");
        vote_contribution(contribution_id).done((res) => {
            count = parseInt($(btn).find(".vote-count").text());
            count = count ? count : 0;
            if (res.message == "vote created") {
                $(btn).addClass("btn-link");
                console.log(count++);
                $(btn).find(".vote-count").text(count);
            } else {
                $(btn).removeClass("btn-link");
                console.log(count--);
                if (count == 0) {
                    $(btn).find(".vote-count").text("");
                    return;
                }
                $(btn).find(".vote-count").text(count);
            }
        })
    })

    // Vote idea
    $(".btn-idea-vote").click(function () {
        let btn = $(this);
        let idea_id = btn.data("idea_id");
        vote_idea(idea_id).done((res) => {
            count = parseInt($(btn).find(".vote-count").text());
            count = count ? count : 0;
            if (res.message == "vote created") {
                $(btn).addClass("btn-link");
                console.log(count++);
                $(btn).find(".vote-count").text(count);
            } else {
                $(btn).removeClass("btn-link");
                console.log(count--);
                if (count == 0) {
                    $(btn).find(".vote-count").text("");
                    return;
                }
                $(btn).find(".vote-count").text(count);
            }
        });
    })

    function delete_contribution(contribution_id) {
        data = JSON.stringify({
            "contribution_id": contribution_id
        })
        return $.ajax({
            headers: {
                "Content-Type": "application/json",
                "X-CSRFToken": csrftoken
            },
            url: "{% url 'contribution-delete-api' %}",
            type: "POST",
            dataType: "json",
            data: data
        });
    }

    function create_contribution(idea_id, parent_id, content) {
        data = JSON.stringify({
            "idea_id": idea_id,
            "parent_id": parent_id,
            "content": content
        })
        return $.ajax({
            headers: {
                "Content-Type": "application/json",
                "X-CSRFToken": csrftoken
            },
            url: "{% url 'contribution-create-api' %}",
            type: "POST",
            dataType: "json",
            data: data
        })
    }

    function vote_contribution(contribution_id) {
        data = JSON.stringify({
            "contribution_id": contribution_id
        })
        return $.ajax({
            headers: {
                "Content-Type": "application/json",
                "X-CSRFToken": csrftoken
            },
            url: "{% url 'vote-api' %}",
            type: "POST",
            dataType: "json",
            data: data
        })
    }

    // focus when click reply button
    $(document).on("click", ".btn-reply", function () {
        let target = $(this).data("target");
        console.log(target)
        $(target).on('shown.bs.collapse', function () {
            let textarea = $(this).find("textarea");
            textarea.focus();
        })
    })
</script>

templates/contribution/contribution.html
{% load voted %}

<div class="mt-3 px-2 border-left-info" id="contribution-{{ contribution.id }}">
    <div class="contribution-content">
        <p class="m-0"> {{ contribution }} </p>
    </div>
    <div class="p-0">
        <div class="mr-3">
            <a href="{% url 'user-detail-page' contribution.user %}">@{{ contribution.user }}</a>
            <span>{{ contribution.date_created | date:"d/m/y H:i"}}</span>
        </div>
        <div class="navbar p-0 justify-content-start">

            <!-- Vote count, voted or not -->
            <div class="{{ contribution.vote_set.all|voted:user }} btn text-decoration-none btn-contribution-vote "
                data-contribution_id="{{ contribution.id }}">
                <span class="h5">
                    {% include "component/vote-icon.html"%}
                </span>
                <span class="vote-count">
                    {% if contribution.vote_set.all.count > 0 %}
                    {{ contribution.vote_set.all.count }}
                    {% endif %}
                </span>
            </div>

            <!-- If contribution is chidrent, form it point to is #children-contribution-form-{{ contribution.parent.id }}-->
            {% if contribution.parent is Null %}
            <span class="btn btn-reply cursor-pointer" data-toggle="collapse"
                data-target="#children-contribution-form-{{ contribution.id }}"
                data-contribution_id="{{ contribution.id }}">Reply</span>
            {% else %}
            <span class="btn btn-reply cursor-pointer" data-toggle="collapse"
                data-target="#children-contribution-form-{{ contribution.parent.id }}"
                data-contribution_id="{{ contribution.id }}">Reply</span>
            {% endif %}

            <!-- If user owns this contribution, this user can delete -->
            <div class="dropup">
                <span class="mr-3 btn cursor-pointer" data-toggle="dropdown"> More</span>
                <div class="dropdown-menu dropdown-menu-right">
                    {% if user == contribution.user  %}
                    <a class="dropdown-item cursor-pointer" data-toggle="modal"
                        data-target="#confirm-delete-contribution"
                        data-parent-contribution-id="{{ contribution.parent.id }}"
                        data-contribution-id="{{contribution.id}}">Delete</a>
                    {% else %}
                    <a class="dropdown-item cursor-not-allowed">Report</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

templates/contribution/list-children-contribution.html
{% for contribution in page_obj %}

<div class="children-contribution" id="children-contribution-{{ contribution.id }}">
    {% include "contribution/contribution.html" with contribution=contribution %}
</div>

{% endfor %}

templates/contribution/list-contribution.html
{% for contribution in page_obj %}
<div id="parent-contribution-{{ contribution.id }}">
    {% include "contribution/contribution.html" with contribution=contribution %}

    <!-- Append list childrens contribution here -->
    <div id="list-children-contribution-{{ contribution.id }}" class="ml-3"></div>
    {% if contribution.children.all.count > 0 %}
    <div class="btn btn-load-more-contribution" id="btn-load-more-children-contribution-{{ contribution.id }}"
        data-next_page_number="1" data-parent_id="{{ contribution.id }}">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
            class="bi bi-arrow-return-right" viewBox="0 0 16 16">
            <path fill-rule="evenodd"
                d="M1.5 1.5A.5.5 0 0 0 1 2v4.8a2.5 2.5 0 0 0 2.5 2.5h9.793l-3.347 3.346a.5.5 0 0 0 .708.708l4.2-4.2a.5.5 0 0 0 0-.708l-4-4a.5.5 0 0 0-.708.708L13.293 8.3H3.5A1.5 1.5 0 0 1 2 6.8V2a.5.5 0 0 0-.5-.5z" />
        </svg>
        <span class="children-count">{{ contribution.children.all.count }}</span>
        <span>more...</span>
        <div class="spinner-border spinner-border-sm loading d-none" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    {% endif %}

    <!-- form create sub contribution -->
    <form class="mt-3 collapse ml-3 create-new-contribution-form" data-idea_id="{{ contribution.idea.id }}"
        id="children-contribution-form-{{ contribution.id }}" data-parent_id="{{ contribution.id }}">
        <div class="text-center loading mb-3 d-none">
            <div class="spinner-border spinner-border-sm" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <div class="border-left-secondary input-group">
            {% csrf_token %}
            <textarea class="form-control" name="content" placeholder="Some contributions..."></textarea>
            <div class="input-group-append">
                <button class="btn btn-outline-secondary btn-create-contribution" type="submit">Send</button>
            </div>
        </div>
        {% if not user.is_authenticated %}
        <p><a href="{% url 'user-login-page' %}?next={{ request.path }}">Login</a> required to make
            contribution!</p>
        {% endif %}
    </form>
</div>
{% endfor %}

templates/contribution/list-sub-contribution.html
{% for contribution in page_obj %}

<div class="sub-contribution" id="sub-contribution-{{ contribution.id }}">
    {% include "contribution/contribution.html" with contribution=contribution %}
</div>

{% endfor %}