idea/urls.py
from django.urls import path
from idea import views


urlpatterns = [
    path("create/", views.idea_create, name="idea-create-page"),
    path("update/<slug:slug>/", views.idea_update, name="idea-update-page"),    
    path("delete/<slug:slug>/", views.idea_delete, name="idea-delete-page"),
    path("<slug:slug>/", views.idea_detail, name="idea-detail-page"),
]

user/urls.py
from django.urls import path, include
from user import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('login/', views.login, name="user-login-page"),
    path('register/', views.register, name="user-register-page"),
    path('logout/', auth_views.LogoutView.as_view(next_page="home-page"),
         name="user-logout"),
    path('profile-setting/', views.profileSetting, name="profile-setting-page"),
    path('user/<slug:username>/', views.user_detail, name="user-detail-page"),
    path('user/edit/<slug:username>/', views.user_edit, name="user-edit-page"),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('read-notify/', views.read_notify, name="api-read-notify"),
    path('list-notify/', views.list_notify, name="api-list-notify"),
]

whatsidea/urls.py
from django.contrib import admin
from django.urls import path, include
from whatsidea.views import homePage, privacyPage, policyPage
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homePage, name="home-page"),
    path('', include('user.urls')),
    path('idea/', include('idea.urls')),
    path('post/', include('post.urls')),
    path('vote/', include('vote.urls')),
    path('contribution/', include('contribution.urls')),
    path('comment/', include('comment.urls')),
    path('image/', include('image.urls')),
    path('privacy/', privacyPage, name="privacy-page"),
    path('policy/', policyPage, name="policy-page"),
    path('like/', include('like.urls')),
    path('inbox/notifications/',
         include(notifications.urls, namespace='notifications')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import uuid


from notifications.signals import notify


def my_handler(sender, instance, created, **kwargs):
    notify.send(instance, verb='was contributed')


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    phone = models.CharField(max_length=30, blank=True)

    def __str__(self):
        return str(self.user)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Idea(models.Model):
    founder = models.ManyToManyField(User)
    title = models.CharField(max_length=500)
    slug = models.SlugField(max_length=500, unique=True, default=uuid.uuid1)
    shortdesc = models.TextField(blank=True)
    content = models.TextField(default="Have no Idea!")
    is_publish = models.BooleanField(default=True)
    is_success = models.BooleanField(default=False)
    address = models.CharField(max_length=200, blank=True)
    phone = models.CharField(max_length=12, blank=True)
    website = models.CharField(max_length=30, blank=True)
    corver_image = models.ImageField(upload_to="media/", blank=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.title)

    class Meta:
        ordering = ["-date_created"]


class Image(models.Model):
    idea = models.ForeignKey(
        Idea, null=True, blank=True, on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    img_file = models.ImageField(upload_to="image")

    def __str__(self):
        return str(self.img_file.url)


class Post(models.Model):
    idea = models.ForeignKey(Idea, on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    content = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.content)

    class Meta:
        ordering = ["-date_created"]


class Contribution(models.Model):
    idea = models.ForeignKey(
        Idea, on_delete=models.CASCADE, null=True, blank=True)
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    parent = models.ForeignKey(
        "self", blank=True, null=True, related_name="children", on_delete=models.CASCADE)
    content = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["date_created"]

    def __str__(self):
        return str(self.content)


@receiver(post_save, sender=Contribution)
def add_notification(sender, instance, **kwargs):
    user_list = instance.idea.founder.all()
    print(instance)
    for user in user_list:
        notify.send(instance.user, recipient=user,
                    verb='contributed', action_object=instance, target=instance.idea)


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, null=True, blank=True)
    parent = models.ForeignKey(
        "self", blank=True, null=True, related_name="children", on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    content = models.TextField()
    date_create = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.content)


class Vote(models.Model):
    idea = models.ForeignKey(
        Idea, null=True, blank=True, on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    contribution = models.ForeignKey(
        Contribution, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return "user:%s  idea:%s" % (str(self.user), str(self.idea))


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_create = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(
        Post, null=True, blank=True, on_delete=models.CASCADE)
    comment = models.ForeignKey(
        Comment, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return "user:%s post:%s" % (str(self.user), str(self.post))

user/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from core import forms
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.models import User
from django.contrib.auth import login as loginMethod, update_session_auth_hash
from django.contrib import messages
from django.http import JsonResponse
from django.template.loader import render_to_string


@login_required()
def read_notify(request):
    request.user.notifications.mark_all_as_read()
    return JsonResponse({
        "message": "notifies readed"
    })


@login_required()
def list_notify(request):
    notifies = request.user.notifications.all()[:10]

    rended_notifies = render_to_string(
        template_name="component/notify.html",
        context={
            "notifies": notifies
        },
        request=request
    )

    return JsonResponse({        
        "notifies": rended_notifies
    })


def login(request):

    if request.user.is_authenticated:
        return redirect("home-page")

    redirect_to = request.GET.get('next', 'home-page')

    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            if user is not None:
                loginMethod(request, user)
                return redirect(redirect_to)
        return render(request, 'user/user-login.html', {
            'form': form
        })
    else:
        return render(request, 'user/user-login.html', {
            'form': AuthenticationForm()
        })


def register(request):

    if request.user.is_authenticated:
        return redirect("home-page")

    redirect_to = request.GET.get('next', '')
    if request.method == "POST":
        form = forms.UserRegisterForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            loginMethod(request, user,
                        backend='django.contrib.auth.backends.ModelBackend')
            return redirect(redirect_to)

        return render(request, 'user/user-register.html', {
            'form': form
        })
    else:
        return render(request, 'user/user-register.html', {
            'form': forms.UserRegisterForm()
        })


@login_required()
def profileSetting(request):
    context = {
        # 'user': user
    }
    return render(request, 'user/user-profile-setting.html', context)


def user_detail(request, username):
    user = get_object_or_404(User, username=username)
    notifies = user.notifications.all()[:15]

    context = {
        'user': user,
        "notifies": notifies
    }
    return render(request, 'user/user-detail.html', context)


@login_required()
def user_edit(request, username):

    if request.method == "POST":
        user_form = forms.UserEditForm(request.POST, instance=request.user)
        profile_form = forms.ProfileForm(
            request.POST, instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            return redirect("user-detail-page", user.username)
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        user_form = forms.UserEditForm(instance=request.user)
        profile_form = forms.ProfileForm(instance=request.user.profile)

    return render(request, 'user/user-edit.html', {
        'user_form': user_form,
        "profile_form": profile_form
    })

templates/user/user-base.html
{% extends 'base.html' %}

{%load static %}
{% load crispy_forms_tags %}

<!-- Extra head here -->
{% block extrahead %}
<title>whatsIdea</title>
<meta name="content" content="">
{% endblock extrahead %}

<!-- Content here -->
{% block content %}
<style>
    img {
        width: 120px;
    }
</style>

<div>
    <div class="row">
        <div class="col-md-7">
            {% block main-content %}
            {% endblock main-content %}
        </div>

        <div class="col-md-5">
         
        </div>
    </div>
</div>
{% endblock content %}

templates/user/user-detail.html
{% extends 'user/user-base.html' %}
{%load static %}
{% load crispy_forms_tags %}
{% load notifications_tags %}

<!-- Extra head here -->
{% block extrahead %}
<title>Profile setting</title>
<meta name="content" content="">
{% endblock extrahead %}



<!-- Content here -->
{% block main-content %}
<main>
    <nav class="navbar px-0 border-bottom">
        <a href="{% url 'user-detail-page' user.username %}">@{{ user }}</a>
        <div class="dropdown">
            <button type="button" class="btn" data-toggle="dropdown">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-three-dots-vertical" fill="currentColor"
                    xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                        d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z">
                    </path>
                </svg>
            </button>
            <div class="dropdown-menu dropdown-menu-right">
                {% if user == request.user  %}
                <a class="dropdown-item" href="{% url 'user-edit-page' user.username %}">Edit</a>
                <a class="dropdown-item" href="{% url 'user-logout' %}">Logout</a>
                {% else %}
                <a class="dropdown-item cursor-not-allowed" href="">Report</a>
                {% endif %}
            </div>
        </div>
    </nav>


    <div class="user-profile mt-3">
        <p class="pl-3">{{ user.profile.bio }}</p>
        <ul>
            <li>First name: {{ user.first_name }}</li>
            <li>Last name: {{ user.last_name }}</li>
            <li>Email: {{ user.email }}</li>
            <li>Phone: {{ user.profile.phone }}</li>
        </ul>
    </div>

    {% if user.idea_set.all.count > 0 %}
    <div class="user-ideas border-top">
        Ideas:
        <ul>
            {% for idea in user.idea_set.all %}
            <li><a href="{% url 'idea-detail-page' idea.slug %}">{{ idea }}</a><br></li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}


</main>

{% endblock main-content %}

templates/user/user-edit.html
{% extends 'user/user-base.html' %}

{%load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}


<!-- Extra head here -->
{% block extrahead %}
<title>whatsIdea</title>
<meta name="content" content="">
{% endblock extrahead %}



<!-- Content here -->
{% block main-content %}
<main>
    <div class="my-3 bg-danger text-white rounded">
        {% if request.method == "POST" %}
        <div class="p-3">{{ user_form.errors }}</div>
        {% endif %}
    </div>

    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            {{ user_form | crispy }}
            {{ profile_form | crispy }}
        </fieldset>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>

</main>

{% endblock main-content %}

templates/user/user-login.html
{% extends 'user/user-base.html' %}

{%load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}

<!-- Extra head here -->
{% block extrahead %}
<title>whatsIdea</title>
<meta name="content" content="">
{% endblock extrahead %}



<!-- Content here -->
{% block main-content %}
<main>
    <legend class="border-bottom mb-4">Welcome to the Idea Land!</legend>
    <div class="social-login pb-3 border-bottom">
        <a class="btn btn-block btn-outline-primary w-100" href="{% url 'social:begin' 'google-oauth2' %}">Login with
            Google</a>
        <a class="btn btn-block btn-outline-primary w-100 mt-3 disabled cursor-not-allowed" href="{% url 'social:begin' 'facebook' %}">Login with Facebook</a>
    </div>
    <form method="POST">
        <p class="h5">Login with your acount:</p>
        {% csrf_token %}
        {{ form | crispy }}

        <div class="form-group">
            <button class="btn btn-primary w-100" type="submit">Login</button>
        </div>
    </form>
    <div class="border-top pt-3">
        <p>Don't have an account? <a href="{% url 'user-register-page' %}?next={{ request.path }}">Register</a></p>
    </div>
</main>

{% endblock main-content %}

templates/user/user-profile-setting.html
{% extends 'user/user-base.html' %}

{%load static %}
{% load crispy_forms_tags %}

<!-- Extra head here -->
{% block extrahead %}
<title>Profile setting</title>
<meta name="content" content="">
{% endblock extrahead %}



<!-- Content here -->
{% block main-content %}
<main>
    <div class="">
        <div class="border-bottom">
            Username: {{ user.username }}
        </div>
        <div class="border-bottom">
            Email: {{ user.email }}
        </div>        
        <div class="border-bottom">
            Phone: {{ user.phone }}
        </div>
    </div>

    <div>
        
        {% for idea in user.idea_set.all %}
            {{ idea }} <br>
        {% endfor %}
            
    </div>

    <a href="{% url 'user-logout' %}" class="btn btn-primary my-3">Logout</a>

</main>

{% endblock main-content %}

templates/user/user-register.html
{% extends 'user/user-base.html' %}

{%load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}


<!-- Extra head here -->
{% block extrahead %}
<title>whatsIdea</title>
<meta name="content" content="">
{% endblock extrahead %}



<!-- Content here -->
{% block main-content %}
<main>
    <legend class="border-bottom mb-4">Welcome to the Idea Land!</legend>

    <div class="social-login pb-3 border-bottom">
        <a class="btn btn-block btn-outline-primary w-100" href="{% url 'social:begin' 'google-oauth2' %}">Register with
            Google</a>
        <a class="btn btn-block btn-outline-primary w-100 mt-3 disabled cursor-not-allowed">Register with Facebook</a>
    </div>

    <div class="my-3 bg-danger text-white rounded">
        {% if request.method == "POST" %}
        <div class="p-3">{{ form.errors }}</div>
        {% endif %}
    </div>
    <form method="POST">
        <p class="h5">Register with your acount:</p>
        {% csrf_token %}
        {{ form | crispy }}
        {% comment %} <div class="form-group">
            <label for="username">Username:</label>
            <input type="text" class="form-control" name="username" id="username" placeholder="Username" required>
        </div>
        <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" class="form-control" name="email" id="email" placeholder="Email" required>
        </div>
        <div class="form-group">
            <label for="password1">Password:</label>
            <input type="password" class="form-control" name="password1" id="password1" placeholder="Password" required>
        </div>
        <div class="form-group">
            <label for="password2">Confirm password:</label>
            <input type="password" class="form-control" name="password2" id="password2" placeholder="Confirm password"
                required>
        </div> {% endcomment %}
        <button type="submit" class="btn btn-primary w-100">Register</button>
    </form>

    <div class="border-top mt-3 pt-3">
        <p>Already have an account? <a href="{% url 'user-login-page' %}?next={{ request.path }}">Login</a></p>
    </div>
</main>

{% endblock main-content %}